/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
#include "mosquitto_internal.h"
#include "time_mosq.h"
/* Header for class com_qichexiaozi_jni_Sub */

#ifndef _Included_com_qichexiaozi_qichediantai_jni_Sub
#define _Included_com_qichexiaozi_qichediantai_jni_Sub
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_qichediantai_jni_Sub
 * Method:    tellSubPath
 * Signature: (Ljava/lang/String;)I
 */
// sub连接到连接服务器
JNIEXPORT jint JNICALL Java_com_qichexiaozi_dtts_service_Connect_subObjectConnectServer
(JNIEnv *env, jobject obj, jobject obj_sub, jint topic_num, jobjectArray topicArray);

// sub切换topic (目前先做保留)
JNIEXPORT jint JNICALL Java_com_qichexiaozi_dtts_service_Connect_subChangeTopic
(JNIEnv *env, jobject obj, jstring old_topic, jstring new_topic);

// 用户进入频道订阅相关topic (进入频道) 
//数组中的第一个元素为主界面的topic, 第二个为自身的topic, 第三个为频道topic
JNIEXPORT jint JNICALL Java_com_qichexiaozi_dtts_service_Connect_subEnterChannel
(JNIEnv *env, jobject obj, jstring channel_topic, jint qos);

// 用户退出频道
//数组中的第一个元素为主界面的topic, 第二个为自身的topic, 第三个为频道topic
JNIEXPORT jint JNICALL Java_com_qichexiaozi_dtts_service_Connect_subQuitChannel
(JNIEnv *env, jobject obj, jstring channel_topic);

#ifdef __cplusplus
}
#endif
#endif

